/*
 * Copyright (C) 2022 thevalidator
 */
package ru.thevalidator.daivinchikmatcher.gui;

import java.awt.Color;
import java.awt.Graphics;
import ru.thevalidator.daivinchikmatcher.property.Property;

/**
 *
 * @author thevalidator <the.validator@yandex.ru>
 */
public class AppWindow extends javax.swing.JFrame {
    
    private Property properties = null;

    /**
     * Creates new form AppWindow
     */
    public AppWindow() {
        initProperties();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        proxyComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        proxyLabel = new javax.swing.JLabel();
        proxyToggleButton = new CustomToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(properties.getAccountNames()));
        jComboBox1.setMinimumSize(new java.awt.Dimension(200, 26));
        jComboBox1.setPreferredSize(new java.awt.Dimension(200, 26));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 250, -1));

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(properties.getUserAgentsNames()));
        jComboBox2.setMinimumSize(new java.awt.Dimension(200, 26));
        jComboBox2.setPreferredSize(new java.awt.Dimension(200, 26));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 250, -1));

        proxyComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        proxyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(properties.getProxyAdresses()));
        proxyComboBox.setMinimumSize(new java.awt.Dimension(200, 26));
        proxyComboBox.setPreferredSize(new java.awt.Dimension(200, 26));
        jPanel1.add(proxyComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 250, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Account:");
        jLabel1.setMinimumSize(new java.awt.Dimension(200, 26));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 26));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 100, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("User agent:");
        jLabel2.setMinimumSize(new java.awt.Dimension(200, 26));
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 26));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 100, -1));

        proxyLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        proxyLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        proxyLabel.setText("Proxy:");
        proxyLabel.setMinimumSize(new java.awt.Dimension(200, 26));
        proxyLabel.setPreferredSize(new java.awt.Dimension(200, 26));
        jPanel1.add(proxyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 100, -1));

        proxyToggleButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        proxyToggleButton.setText("OFF");
        proxyToggleButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        proxyToggleButton.setMaximumSize(new java.awt.Dimension(60, 26));
        proxyToggleButton.setMinimumSize(new java.awt.Dimension(60, 26));
        proxyToggleButton.setOpaque(true);
        proxyToggleButton.setPreferredSize(new java.awt.Dimension(60, 26));
        proxyToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proxyToggleButtonActionPerformed(evt);
            }
        });
        jPanel1.add(proxyToggleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void initProperties() {
        properties = Property.readFromJson(Property.PROP_FILE);
    }
    
    private void proxyToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proxyToggleButtonActionPerformed
        if (proxyToggleButton.isSelected()) {
            proxyComboBox.setEnabled(false);
            proxyToggleButton.setText("ON");
        } else {
            proxyComboBox.setEnabled(true);
            proxyToggleButton.setText("OFF");
        }
    }//GEN-LAST:event_proxyToggleButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> proxyComboBox;
    private javax.swing.JLabel proxyLabel;
    private javax.swing.JToggleButton proxyToggleButton;
    // End of variables declaration//GEN-END:variables
}
